### ISSUE TITLE
Emote Issue | Input string was not in a correct format

### ISSUE THREAD

**Issue by StephenMP** [TwitchLib/TwitchLib.Client#141]
There seems to be some sort of issue when attempting to parse emotes. Potentially with emotes which contain numbers. This exists in the latest version of TwitchLib (v. 3.1.0)

```
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at TwitchLib.Client.Models.EmoteSet..ctor(String emoteSetData, String message)
   at TwitchLib.Client.Models.ChatMessage..ctor(String botUsername, IrcMessage ircMessage, MessageEmoteCollection& emoteCollection, Boolean replaceEmotes)
   at TwitchLib.Client.TwitchClient.HandlePrivMsg(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient.HandleIrcMessage(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient._client_OnMessage(Object sender, OnMessageEventArgs e)
   at TwitchLib.Communication.Clients.WebSocketClient.<<StartListenerTask>b__68_0>d.MoveNext()
```

**Comment by Syzuna** [comment]
most likely wont fix/add this in the current version.
the emote code will be revisited for v4/the rewrite of the client tho

**Comment by Buguito** [comment]
I'm having this same issue while listening to messages on a Twitch channel which well, crashes the library and renders it useless. Any hint on where could i apply a hot fix?

Warm Regards,
Alan

**Comment by StephenMP** [comment]
May as well close this :)
